version: '3'
services:
  login-app:
    container_name: usertours-app
    image: usertours/appv1
    restart: always
    build: .
    ports:
      - '8000:8000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - C:\Program Files\MongoDB\Server\6.0\data:/data/db
    ports:
      - '27017:27017'
